spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: eden*ex7
    jdbc-url: jdbc:mysql://127.0.0.1:3306/elasticsearch?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT