server:
  port: 8080
  error:
    whitelabel:
      enabled: false  #不让springboot自动生成whitelabel这个页面

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
  devtools:
    restart:
      exclude: templates/**,static/** #springboot devtools是全局监听的，去掉前端修改引起的没必要热加载。因为设置了thymeleaf不使用cache

logging:
  level:
    org:
      hibernate:
        SQL: debug

#security:  2.x已经废弃，在启动类中排除
#  basic:
#    enabled: false
