server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #validate
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug

#security:  2.x已经废弃，在启动类中排除
#  basic:
#    enabled: false
